# Generated by Django 2.1 on 2018-08-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20180819_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='utensil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Utensil'),
        ),
    ]
