# Generated by Django 2.1 on 2018-08-19 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20180819_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredient'),
        ),
    ]
