# Generated by Django 2.1 on 2018-08-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20180819_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
