# Generated by Django 2.1 on 2018-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_step_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='utensil',
        ),
        migrations.RemoveField(
            model_name='step',
            name='action',
        ),
        migrations.RemoveField(
            model_name='step',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='step',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='step',
            name='vars',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
